# Generated by Django 5.2.4 on 2025-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('portfolio', 'Портфоліо'), ('prices', 'Ціни'), ('education', 'Навчання'), ('faq', 'FAQ'), ('blog', 'Блог'), ('contacts', 'Контакти')], max_length=20, verbose_name='Сторінка')),
                ('block_type', models.CharField(choices=[('hero', 'Герой секція'), ('content', 'Контент блок'), ('features', 'Особливості'), ('testimonials', 'Відгуки'), ('cta', 'Заклик до дії')], max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Колір фону')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Колір тексту')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Блок сторінки',
                'verbose_name_plural': 'Блоки сторінок',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('portfolio', 'Портфоліо'), ('prices', 'Ціни'), ('education', 'Навчання'), ('faq', 'FAQ'), ('blog', 'Блог'), ('contacts', 'Контакти')], max_length=20, unique=True, verbose_name='Сторінка')),
                ('title', models.CharField(max_length=200, verbose_name='SEO заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='SEO опис')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='SEO ключові слова')),
            ],
            options={
                'verbose_name': 'Метадані сторінки',
                'verbose_name_plural': 'Метадані сторінок',
            },
        ),
    ]
